#!/bin/bash
cd /opt/webchat/app

if [ -z $1 ]
then
/opt/webchat/python/bin/python manage.pyc whatsapp
else
mkdir $(eval echo ~/.firefox.default.$1)
CUSRHD=$(eval echo ~/.firefox.default.$1)

/opt/webchat/python/bin/python manage.pyc whatsapp --id=$1 --profile=$CUSRHD
fi
